name: Auto Assign PR

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
      - name: Auto-assign PR to Creator
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: context.issue.number,
              assignees: [context.payload.pull_request.user.login]
            });
