name: Auto Assign PR

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    
    steps:
      - name: Auto-assign PR to Creator
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const pr = context.payload.pull_request;
              console.log('PR Details:', {
                owner: context.repo.owner,
                repo: context.repo.name,
                issue_number: pr.number,
                assignee: pr.user.login
              });
              
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.name,
                issue_number: pr.number,
                assignees: [pr.user.login]
              });
              
              console.log('Successfully assigned PR to:', pr.user.login);
            } catch (error) {
              console.log('Error details:', error);
              core.setFailed(error.message);
            }
